
using UnityEngine;

 public abstract class EnemyBase : MonoBehaviour
 {
     public float health = 30f;                                                  // Enemy health points
     public float damage = 10f;                                                  // damage generated by the enemy when type the wrong key
     public float timer = 30f;                                                   // time limit for the player 

     // Coin reward for defeating the enemy, with some variance to add unpredictability
     private int coinReward = 10;                                               
     private int coinVariance = 5;

    public virtual void TakeDamage(int letterAmount, float multiplier = 1f)     // Method to apply damage to the enemy, if the input is 100% correct
     {
         float finalDamage = letterAmount * multiplier;                         
         health -= finalDamage;
         if (health <= 0)
         {
             Die();
         }
     }

     protected virtual void Die()
     {
        // Play death animation or effects here
        // calculate the actual coin reward with variance, ensuring it doesn't go below 0
        int actualReward = coinReward + Random.Range(-coinVariance, coinVariance + 1);
        actualReward = Mathf.Max(0, actualReward);

        // use add coins from GameManager to add coins to the player's total
        if (GameManager.Instance != null)
        {
            GameManager.Instance.AddCoins(actualReward);
        }

        Destroy(gameObject);                                                     // Remove the enemy from the scene
     }

     public virtual void AttackingMethod()
     {
         // Implement the way how enemy attacks the player (short words, long words, sentences, articles, etc.)
         Debug.Log($"Enemy attacks player for {damage} damage!");
     }
 }
