using UnityEngine;

public abstract class EnemyBase : MonoBehaviour
{
    public float health = 30f;                                                  // Enemy health points
    public float damage = 10f;                                                  // damage generated by the enemy when type the wrong key
    public float timer = 30f;                                                   // time limit for the player 

    public virtual void TakeDamage(int letterAmount, float multiplier = 1f)     // Method to apply damage to the enemy, if the input is 100% correct
    {
        float finalDamage = letterAmount * multiplier;                         
        health -= finalDamage;
        if (health <= 0)
        {
            Die();
        }
    }

    protected virtual void Die()
    {
        // Play death animation or effects here
        Destroy(gameObject);                                                     // Remove the enemy from the scene
    }

    public virtual void AttackingMethod()
    {
        // Implement the way how enemy attacks the player (short words, long words, sentences, articles, etc.)
        Debug.Log($"Enemy attacks player for {damage} damage!");
    }
}
